### ISSUE TITLE
Escape sequence behavior is incorrect.

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Diffmark#1]
Patterns be classified wrongly by escaping a control symbol at the beginning or end of a pattern. For example, this should be an *appending* add pattern, but instead, it parses to a *prepending* add pattern:
```
test\+
```
I'll probably switch over to a proper lexer in order to fix this.

**Comment by jakwings** [comment]
Hey, thanks for your interesting ideas. I have written myself a variant of Diffmark in JavaScript. I'm here to inform you because I can't find detailed specs for the pattern string and I found some not so intelligible patterns in [Rantionay](https://github.com/TheBerkin/Rantionary), e.g.

1. https://github.com/TheBerkin/Rantionary/blob/12dc7d000be40b6d587615028c2186166acdde3b/Adjectives.dic#L95 (better: `red-hot/*glowing\-red heat`)
2. https://github.com/TheBerkin/Rantionary/blob/12dc7d000be40b6d587615028c2186166acdde3b/Adjectives.dic#L203 (better: `jealous/*envy`)
3. https://github.com/TheBerkin/Rantionary/blob/12dc7d000be40b6d587615028c2186166acdde3b/Adjectives.dic#L133 (better: `wet/*moisture`)
4. https://github.com/TheBerkin/Rantionary/blob/12dc7d000be40b6d587615028c2186166acdde3b/Colors.dic#L20 (longer but less ambiguous: `lime green/------\-green\-ish`)
5. https://github.com/TheBerkin/Rantionary/blob/12dc7d000be40b6d587615028c2186166acdde3b/Adjectives.dic#L491 (shorter and less ambiguous: `fluttering/*light\-weightedness`)

So, welcome to try my project “[diff-mark](https://github.com/jakwings/diff-mark)” and gain new insights into this. :tada: (see the [online demo](http://jakwings.github.io/diff-mark/)) Just FYI

**Comment by TheBerkin** [comment]
You did a great job with this JS port. I am impressed! Have a star.

I should mention that those patterns in Rantionary are generated using `Diff.Derive`, so they might not be optimal.

The Diffmark language is tiny; the README is essentially the spec. However, if you believe something could be made more clear, don't hesitate to let me know.

**Comment by jakwings** [comment]
The biggest problem, I think, is when special characters are mixed together, like `+de-`, `--alf-year`, or used without specs, like `|`, `a|b`, `+`, `*`, `a+b`, `a*b`, then it is hard to tell what they mean. I would count such patterns as faults without deep thoughts. I don't know C# so I can just provide you my C like JavaScript code. ;-)

**Comment by TheBerkin** [comment]
You have a good point, and I should do more to address those in my documentation. To address the symbol-string symmetry cases like `-de-`, Diffmark has a bias on whether it chooses to treat it as a prefix or postfix (it chooses postfix in that case). I will try to clarify this in my readme.
